version: "3.6"
services:
  autoscenario-db:
    image: postgis/postgis
    restart: always
    volumes:
      - autoscenario_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
  autoscenario-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin123
    ports:
      - "8081:80"
    depends_on:
    - autoscenario-db
volumes:
  autoscenario_data:
